/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Contributors: typeof import('./../../docs/.vitepress/theme/components/Contributors.vue')['default']
    MyLayout: typeof import('./../../docs/.vitepress/theme/components/MyLayout.vue')['default']
  }
}
